"""SyntheticAugmentedDataset — merges real emails with LLM-generated hard negatives.

The synthetic dataset is produced by scripts/generate_synthetic_emails.py.
Each real sender "alice@enron.com" gets a paired synthetic sender
"alice@enron.com__syn" whose emails mimic Alice's style but were generated by
an LLM.  In contrastive training the loss must separate real-Alice from
synthetic-Alice, which requires learning subtler stylometric features than
simply separating Alice from random other senders.

Usage with PKSampler (random pairing — simple):
    real_ds = EnronDataset(cfg.data, split="train")
    full_ds = SyntheticAugmentedDataset(real_ds, cfg.data.augmentation.synthetic_path)
    sampler = PKSampler(full_ds.sender_ids, p=cfg.p, k=cfg.k)

Usage with SyntheticBalancedSampler (guaranteed pairing per batch — recommended):
    sampler = SyntheticBalancedSampler(full_ds.sender_ids, p=P, k=K, n_syn=2)
"""

from __future__ import annotations

from email_fraud.data.base import BaseDataset

SYN_SUFFIX = "__syn"


class SyntheticAugmentedDataset(BaseDataset):
    """Concatenates a real BaseDataset with an Arrow-backed synthetic dataset.

    The combined dataset exposes the same (text, sender_id) interface as
    EnronDataset so it works transparently with PKSampler and episode_collate.

    Args:
        real_dataset: Any BaseDataset (typically EnronDataset for the train split).
        synthetic_path: Path to the Arrow dataset produced by
                        scripts/generate_synthetic_emails.py.
    """

    def __init__(self, real_dataset: BaseDataset, synthetic_path: str) -> None:
        from datasets import load_from_disk

        syn_ds = load_from_disk(synthetic_path)

        self._texts: list[str] = list(real_dataset._texts) + list(syn_ds["text"])
        self._sender_ids_list: list[str] = (
            list(real_dataset._sender_ids_list) + list(syn_ds["sender_id"])
        )

    def __len__(self) -> int:
        return len(self._texts)

    def __getitem__(self, index: int) -> tuple[str, str]:
        return self._texts[index], self._sender_ids_list[index]

    @property
    def sender_ids(self) -> list[str]:
        return self._sender_ids_list
